version: "3.8"

services:
  db:
    image: postgres:15.2
    container_name: db_clean_architecture_example
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=db_clean_architecture_example
      - POSTGRES_DB=db_clean_architecture_example

  redis:
    image: redis:7.0.11-alpine
    container_name: redis_clean_architecture_example
    restart: always
    ports:
      - 6379:6379
