CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL,

    level INTEGER DEFAULT 1 NOT NULL,
    exp BIGINT DEFAULT 0 NOT NULL,
    next_level_exp INTEGER DEFAULT 0 NOT NULL,

    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
